#!/bin/bash
# Quick API Endpoint Test Examples for Story 8.4
# These commands demonstrate the endpoint structure (auth token needed for actual testing)

echo "=================================================="
echo "Story 8.4: Interview History API Test Examples"
echo "=================================================="
echo ""

echo "Prerequisites:"
echo "1. Backend server running: http://localhost:8000"
echo "2. Get auth token: export TOKEN=\$(curl -s -X POST 'http://localhost:8000/api/v1/auth/login' -H 'Content-Type: application/json' -d '{\"email\":\"test@example.com\",\"password\":\"password\"}' | grep -o '\"access_token\":\"[^\"]*\"' | cut -d'\"' -f4)"
echo ""

echo "=================================================="
echo "Test 1: List Interview Sessions"
echo "=================================================="
echo ""
echo "# Basic list (default: page 1, 10 items, sort by created_at desc)"
echo "curl -X GET 'http://localhost:8000/api/v1/interviews' \\"
echo "  -H \"Authorization: Bearer \$TOKEN\""
echo ""
echo "# With pagination and sorting"
echo "curl -X GET 'http://localhost:8000/api/v1/interviews?page=1&page_size=5&sort_by=overall_score&sort_order=desc' \\"
echo "  -H \"Authorization: Bearer \$TOKEN\""
echo ""
echo "# Filter by status"
echo "curl -X GET 'http://localhost:8000/api/v1/interviews?status=completed' \\"
echo "  -H \"Authorization: Bearer \$TOKEN\""
echo ""

echo "=================================================="
echo "Test 2: Get Interview Detail"
echo "=================================================="
echo ""
echo "# Get session metadata (replace SESSION_ID)"
echo "curl -X GET 'http://localhost:8000/api/v1/interviews/{SESSION_ID}/detail' \\"
echo "  -H \"Authorization: Bearer \$TOKEN\""
echo ""

echo "=================================================="
echo "Test 3: Get Interview Transcript"
echo "=================================================="
echo ""
echo "# Get full Q&A conversation (replace SESSION_ID)"
echo "curl -X GET 'http://localhost:8000/api/v1/interviews/{SESSION_ID}/transcript' \\"
echo "  -H \"Authorization: Bearer \$TOKEN\""
echo ""

echo "=================================================="
echo "Test 4: Get Evaluation Detail"
echo "=================================================="
echo ""
echo "# Get comprehensive evaluation report (replace SESSION_ID)"
echo "curl -X GET 'http://localhost:8000/api/v1/interviews/{SESSION_ID}/evaluation/detail' \\"
echo "  -H \"Authorization: Bearer \$TOKEN\""
echo ""

echo "=================================================="
echo "Expected Response Structures"
echo "=================================================="
echo ""
echo "1. PaginatedInterviewSessions:"
echo "   { items: [], total: 0, page: 1, page_size: 10, total_pages: 0 }"
echo ""
echo "2. InterviewSessionDetail:"
echo "   { id, job_title, job_description, position_level, created_at, "
echo "     completed_at, status, duration_minutes, overall_score, "
echo "     overall_grade, hiring_recommendation, question_count, turn_count }"
echo ""
echo "3. InterviewTranscriptResponse:"
echo "   { interview_id, job_title, total_turns, turns: [ "
echo "     { turn_number, question_text, question_type, candidate_message, "
echo "       ai_response, scores, action_type, created_at } ] }"
echo ""
echo "4. InterviewEvaluationDetail:"
echo "   { interview_id, job_title, overall_evaluation, dimension_scores, "
echo "     detailed_analysis, recommendations, created_at }"
echo ""

echo "=================================================="
echo "Swagger UI Documentation"
echo "=================================================="
echo ""
echo "Open in browser: http://localhost:8000/docs"
echo "  → Expand 'interviews' section"
echo "  → Find Story 8.4 endpoints (marked with [Story 8.4])"
echo "  → Click 'Try it out' to test interactively"
echo ""

echo "=================================================="
echo "Postman/Thunder Client Collection"
echo "=================================================="
echo ""
echo "Import this OpenAPI spec:"
echo "  http://localhost:8000/openapi.json"
echo ""
echo "Or manually create requests with:"
echo "  - Base URL: http://localhost:8000/api/v1"
echo "  - Authorization: Bearer Token (from login)"
echo "  - Content-Type: application/json"
echo ""
