"""
SQLAlchemy models for Epic 8: Virtual AI Interview Room.

This module defines database models for AI-powered interview sessions:
- InterviewSession: Main interview session tracking
- InterviewQuestion: AI-generated questions
- InterviewTurn: Conversation history with per-turn evaluation
- InterviewEvaluation: Final comprehensive evaluation report
- AgentCallLog: Monitoring and debugging agent performance
"""
import uuid
from datetime import datetime
from decimal import Decimal
from typing import List, TYPE_CHECKING, Optional

from sqlalchemy import Boolean, DateTime, ForeignKey, Integer, Numeric, String, Text
from sqlalchemy.dialects.postgresql import UUID, JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.database import Base

if TYPE_CHECKING:
    from app.modules.users.models import User


class InterviewSession(Base):
    """
    Interview session model for AI interview practice.
    
    Tracks the overall interview session from creation to completion.
    Links to job postings (optional) and candidates (required).
    """
    __tablename__ = "interview_sessions"
    
    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    job_posting_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True), nullable=True
    )
    candidate_id: Mapped[int] = mapped_column(
        ForeignKey("users.id", ondelete="CASCADE"), 
        nullable=False,
        index=True
    )
    status: Mapped[str] = mapped_column(
        String(20), 
        nullable=False, 
        default="pending"
    )  # 'pending', 'in_progress', 'completed', 'cancelled'
    scheduled_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    started_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    completed_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    duration_minutes: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=datetime.utcnow
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), 
        default=datetime.utcnow, 
        onupdate=datetime.utcnow
    )
    
    # Relationships
    questions: Mapped[List["InterviewQuestion"]] = relationship(
        "InterviewQuestion",
        back_populates="session",
        cascade="all, delete-orphan",
        order_by="InterviewQuestion.order_index"
    )
    turns: Mapped[List["InterviewTurn"]] = relationship(
        "InterviewTurn",
        back_populates="session",
        cascade="all, delete-orphan",
        order_by="InterviewTurn.turn_number"
    )
    evaluation: Mapped[Optional["InterviewEvaluation"]] = relationship(
        "InterviewEvaluation",
        back_populates="session",
        uselist=False
    )
    candidate: Mapped["User"] = relationship(
        "User", 
        foreign_keys=[candidate_id],
        lazy="selectin"
    )


class InterviewQuestion(Base):
    """
    AI-generated interview question model.
    
    Stores questions generated by QuestionCraft AI agent.
    Each question includes metadata for evaluation guidance.
    """
    __tablename__ = "interview_questions"
    
    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    interview_session_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("interview_sessions.id", ondelete="CASCADE"),
        nullable=False,
        index=True
    )
    question_id: Mapped[str] = mapped_column(
        String(50), nullable=False
    )  # e.g., "Q1", "Q2"
    category: Mapped[str] = mapped_column(
        String(20), nullable=False
    )  # 'technical', 'behavioral', 'situational'
    difficulty: Mapped[str] = mapped_column(
        String(20), nullable=False
    )  # 'junior', 'middle', 'senior'
    question_text: Mapped[str] = mapped_column(Text, nullable=False)
    key_points: Mapped[Optional[dict]] = mapped_column(JSONB, nullable=True)
    ideal_answer_outline: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    evaluation_criteria: Mapped[Optional[dict]] = mapped_column(JSONB, nullable=True)
    order_index: Mapped[int] = mapped_column(Integer, nullable=False)
    is_selected: Mapped[bool] = mapped_column(Boolean, default=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=datetime.utcnow
    )
    
    # Relationships
    session: Mapped["InterviewSession"] = relationship(
        "InterviewSession", back_populates="questions"
    )
    turns: Mapped[List["InterviewTurn"]] = relationship(
        "InterviewTurn", back_populates="question"
    )


class InterviewTurn(Base):
    """
    Conversation turn model for interview dialogue.
    
    Records each Q&A exchange with real-time evaluation from DialogFlow AI.
    Stores per-turn scoring and observations.
    """
    __tablename__ = "interview_turns"
    
    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    interview_session_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("interview_sessions.id", ondelete="CASCADE"),
        nullable=False,
        index=True
    )
    question_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("interview_questions.id", ondelete="SET NULL"),
        nullable=True
    )
    turn_number: Mapped[int] = mapped_column(Integer, nullable=False)
    ai_message: Mapped[str] = mapped_column(Text, nullable=False)
    candidate_message: Mapped[str] = mapped_column(Text, nullable=False)
    answer_quality: Mapped[Optional[dict]] = mapped_column(
        JSONB, nullable=True
    )  # {technical_accuracy, communication_clarity, depth_of_knowledge, overall_score}
    key_observations: Mapped[Optional[dict]] = mapped_column(JSONB, nullable=True)
    strengths: Mapped[Optional[dict]] = mapped_column(JSONB, nullable=True)
    gaps: Mapped[Optional[dict]] = mapped_column(JSONB, nullable=True)
    action_type: Mapped[Optional[str]] = mapped_column(
        String(20), nullable=True
    )  # 'continue', 'follow_up', 'next_question', 'end_interview'
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=datetime.utcnow
    )
    
    # Relationships
    session: Mapped["InterviewSession"] = relationship(
        "InterviewSession", back_populates="turns"
    )
    question: Mapped[Optional["InterviewQuestion"]] = relationship(
        "InterviewQuestion", back_populates="turns"
    )


class InterviewEvaluation(Base):
    """
    Final evaluation report model.
    
    Comprehensive assessment generated by EvalMaster AI after interview completion.
    Includes dimension scores, detailed analysis, and hiring recommendation.
    """
    __tablename__ = "interview_evaluations"
    
    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    interview_session_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("interview_sessions.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
        unique=True
    )
    final_score: Mapped[Decimal] = mapped_column(
        Numeric(3, 1), nullable=False
    )  # 0.0 - 10.0
    grade: Mapped[str] = mapped_column(
        String(20), nullable=False
    )  # 'excellent', 'good', 'average', 'poor'
    hiring_recommendation: Mapped[str] = mapped_column(
        String(20), nullable=False
    )  # 'strong_hire', 'hire', 'consider', 'no_hire'
    dimension_scores: Mapped[dict] = mapped_column(
        JSONB, nullable=False
    )  # 3-dimension scoring structure
    detailed_analysis: Mapped[dict] = mapped_column(
        JSONB, nullable=False
    )  # strengths, weaknesses, notable_moments, red_flags
    recommendations: Mapped[dict] = mapped_column(
        JSONB, nullable=False
    )  # hiring_decision, reasoning, suggestions
    evaluation_metadata: Mapped[Optional[dict]] = mapped_column(
        JSONB, nullable=True
    )  # total_questions, duration, etc.
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=datetime.utcnow
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), 
        default=datetime.utcnow, 
        onupdate=datetime.utcnow
    )
    
    # Relationships
    session: Mapped["InterviewSession"] = relationship(
        "InterviewSession", back_populates="evaluation"
    )


class AgentCallLog(Base):
    """
    Agent monitoring log model.
    
    Tracks all AI agent invocations for performance monitoring and debugging.
    Records input, output, status, latency, and errors.
    """
    __tablename__ = "agent_call_logs"
    
    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    agent_type: Mapped[str] = mapped_column(
        String(50), nullable=False
    )  # 'question_generator', 'conversation', 'evaluator'
    interview_session_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("interview_sessions.id", ondelete="SET NULL"),
        nullable=True,
        index=True
    )
    input_data: Mapped[Optional[dict]] = mapped_column(JSONB, nullable=True)
    output_data: Mapped[Optional[dict]] = mapped_column(JSONB, nullable=True)
    status: Mapped[str] = mapped_column(
        String(20), nullable=False
    )  # 'success', 'error'
    error_message: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    latency_ms: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    model_used: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=datetime.utcnow, index=True
    )
