"""add_async_status_and_error_message_to_interview_sessions

Revision ID: 2cbc6f2d2a19
Revises: 2141c520a6bc
Create Date: 2026-01-11 12:10:33.914238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2cbc6f2d2a19'
down_revision: Union[str, Sequence[str], None] = '2141c520a6bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cv_analyses')
    op.drop_index(op.f('ix_agent_call_logs_session_id'), table_name='agent_call_logs')
    op.create_index(op.f('ix_agent_call_logs_interview_session_id'), 'agent_call_logs', ['interview_session_id'], unique=False)
    op.drop_index(op.f('ix_interview_evaluations_session_id'), table_name='interview_evaluations')
    op.create_index(op.f('ix_interview_evaluations_interview_session_id'), 'interview_evaluations', ['interview_session_id'], unique=True)
    op.drop_index(op.f('ix_interview_questions_session_id'), table_name='interview_questions')
    op.create_index(op.f('ix_interview_questions_interview_session_id'), 'interview_questions', ['interview_session_id'], unique=False)
    op.add_column('interview_sessions', sa.Column('error_message', sa.Text(), nullable=True))
    op.drop_index(op.f('ix_interview_sessions_status'), table_name='interview_sessions')
    op.drop_index(op.f('ix_interview_turns_session_id'), table_name='interview_turns')
    op.drop_index(op.f('ix_interview_turns_session_turn'), table_name='interview_turns')
    op.create_index(op.f('ix_interview_turns_interview_session_id'), 'interview_turns', ['interview_session_id'], unique=False)
    op.drop_index(op.f('idx_job_descriptions_benefits_gin'), table_name='job_descriptions', postgresql_using='gin')
    op.drop_index(op.f('idx_job_descriptions_job_type'), table_name='job_descriptions')
    op.drop_index(op.f('idx_job_descriptions_required_skills_gin'), table_name='job_descriptions', postgresql_using='gin')
    op.drop_index(op.f('idx_job_descriptions_salary'), table_name='job_descriptions', postgresql_where='((salary_min IS NOT NULL) OR (salary_max IS NOT NULL))')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_job_descriptions_salary'), 'job_descriptions', ['salary_min', 'salary_max'], unique=False, postgresql_where='((salary_min IS NOT NULL) OR (salary_max IS NOT NULL))')
    op.create_index(op.f('idx_job_descriptions_required_skills_gin'), 'job_descriptions', ['required_skills'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_job_descriptions_job_type'), 'job_descriptions', ['job_type'], unique=False)
    op.create_index(op.f('idx_job_descriptions_benefits_gin'), 'job_descriptions', ['benefits'], unique=False, postgresql_using='gin')
    op.drop_index(op.f('ix_interview_turns_interview_session_id'), table_name='interview_turns')
    op.create_index(op.f('ix_interview_turns_session_turn'), 'interview_turns', ['interview_session_id', 'turn_number'], unique=False)
    op.create_index(op.f('ix_interview_turns_session_id'), 'interview_turns', ['interview_session_id'], unique=False)
    op.create_index(op.f('ix_interview_sessions_status'), 'interview_sessions', ['status'], unique=False)
    op.drop_column('interview_sessions', 'error_message')
    op.drop_index(op.f('ix_interview_questions_interview_session_id'), table_name='interview_questions')
    op.create_index(op.f('ix_interview_questions_session_id'), 'interview_questions', ['interview_session_id'], unique=False)
    op.drop_index(op.f('ix_interview_evaluations_interview_session_id'), table_name='interview_evaluations')
    op.create_index(op.f('ix_interview_evaluations_session_id'), 'interview_evaluations', ['interview_session_id'], unique=False)
    op.drop_index(op.f('ix_agent_call_logs_interview_session_id'), table_name='agent_call_logs')
    op.create_index(op.f('ix_agent_call_logs_session_id'), 'agent_call_logs', ['interview_session_id'], unique=False)
    op.create_table('cv_analyses',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('cv_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), server_default=sa.text("'PENDING'::character varying"), autoincrement=False, nullable=False),
    sa.Column('ai_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ai_summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ai_feedback', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('extracted_skills', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('skill_breakdown', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('skill_categories', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('skill_recommendations', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['cv_id'], ['cvs.id'], name=op.f('cv_analyses_cv_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('cv_analyses_pkey'))
    )
    # ### end Alembic commands ###
