"""Manually sync users table schema with models.py and add birthday

Revision ID: 2d6cc6c46951
Revises: 
Create Date: 2025-12-08 11:54:44.734128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.sql import func


# revision identifiers, used by Alembic.
revision: str = '2d6cc6c46951'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Rename columns: hash_password to hashed_password
    op.alter_column('users', 'hash_password', new_column_name='hashed_password', existing_type=sa.VARCHAR(), nullable=False)
    # Rename columns: is_activate to is_active
    op.alter_column('users', 'is_activate', new_column_name='is_active', existing_type=sa.BOOLEAN(), nullable=False)

    # Alter full_name nullability: from NOT NULL to NULLABLE
    op.alter_column('users', 'full_name', existing_type=sa.VARCHAR(), nullable=True)

    # Drop old role column (which has userrole enum)
    op.drop_column('users', 'role')
    # Add new role column as String with a default of "user"
    op.add_column('users', sa.Column('role', sa.String(), nullable=False, server_default='user'))

    # Add new columns
    op.add_column('users', sa.Column('birthday', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('is_scraped', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('users', sa.Column('avatar', sa.String(), nullable=True))
    op.add_column('users', sa.Column('activation_code', sa.String(), nullable=True))
    op.add_column('users', sa.Column('activation_code_expires_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('password_reset_code', sa.String(), nullable=True))
    op.add_column('users', sa.Column('password_reset_code_expires_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=func.now()))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=func.now(), onupdate=func.now()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove newly added columns
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'password_reset_code_expires_at')
    op.drop_column('users', 'password_reset_code')
    op.drop_column('users', 'activation_code_expires_at')
    op.drop_column('users', 'activation_code')
    op.drop_column('users', 'avatar')
    op.drop_column('users', 'is_scraped')
    op.drop_column('users', 'birthday')

    # Drop new role column
    op.drop_column('users', 'role')
    # Add back old role column (userrole enum) - Assuming userrole enum was handled by previous migration or manually.
    # This might require recreation of the enum type if it's completely gone. For now, assume it exists.
    # If the enum type was never defined by Alembic, you might need op.create_enum() here.
    # For simplicity in downgrade, assuming the enum type 'userrole' still exists or will be handled.
    op.add_column('users', sa.Column('role', postgresql.ENUM('ADMIN', 'USER', 'GUEST', name='userrole'), autoincrement=False, nullable=False))


    # Alter full_name nullability: from NULLABLE to NOT NULL
    op.alter_column('users', 'full_name', existing_type=sa.VARCHAR(), nullable=False)

    # Rename columns back: hashed_password to hash_password
    op.alter_column('users', 'hashed_password', new_column_name='hash_password', existing_type=sa.VARCHAR(), nullable=False)
    # Rename columns back: is_active to is_activate
    op.alter_column('users', 'is_active', new_column_name='is_activate', existing_type=sa.BOOLEAN(), nullable=False)
    # ### end Alembic commands ###