"""add benefits to job_descriptions

Revision ID: 38278631803e
Revises: f8d39048488d
Create Date: 2026-01-06 17:40:07.970820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '38278631803e'
down_revision: Union[str, Sequence[str], None] = 'f8d39048488d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_descriptions', sa.Column('benefits', postgresql.ARRAY(sa.Text()), nullable=True))
    op.create_index('idx_job_descriptions_benefits_gin', 'job_descriptions', ['benefits'], postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_job_descriptions_benefits_gin', table_name='job_descriptions', postgresql_using='gin')
    op.drop_column('job_descriptions', 'benefits')
    # ### end Alembic commands ###
