"""Create cvs table

Revision ID: 5537984ec864
Revises: 2d6cc6c46951
Create Date: 2025-12-11 14:49:35.599313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5537984ec864'
down_revision: Union[str, Sequence[str], None] = '2d6cc6c46951'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cvs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('users', 'is_scraped',
               existing_type=sa.BOOLEAN(),
               comment='Đánh dấu tài khoản cào về',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_hash_password_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_hash_password_key'), 'users', ['hashed_password'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'is_scraped',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Đánh dấu tài khoản cào về',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_table('cvs')
    # ### end Alembic commands ###
