"""add_job_descriptions_table

Revision ID: 609a832b1945
Revises: f7a3b2c1d4e5
Create Date: 2025-12-17 18:44:31.820054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '609a832b1945'
down_revision: Union[str, Sequence[str], None] = 'f7a3b2c1d4e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_descriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('required_skills', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('min_experience_years', sa.Integer(), nullable=True),
    sa.Column('location_type', sa.String(length=50), nullable=False),
    sa.Column('salary_min', sa.Integer(), nullable=True),
    sa.Column('salary_max', sa.Integer(), nullable=True),
    sa.Column('parsed_requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('embedding', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint("location_type IN ('remote', 'hybrid', 'on-site')", name='check_location_type'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_descriptions_user_id'), 'job_descriptions', ['user_id'], unique=False)
    # Create GIN index for required_skills array for efficient queries
    op.create_index('ix_job_descriptions_required_skills', 'job_descriptions', ['required_skills'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_job_descriptions_required_skills', table_name='job_descriptions')
    op.drop_index(op.f('ix_job_descriptions_user_id'), table_name='job_descriptions')
    op.drop_table('job_descriptions')
    # ### end Alembic commands ###
